import { createAction } from 'redux-actions';

const ADD_DOCUMENT_PERSONAL = 'ADD_DOCUMENT_PERSONAL';
const REMOVE_DOCUMENT_PERSONAL = 'REMOVE_DOCUMENT_PERSONAL';
const SET_SHAREABLE_PERSONAL = 'SET_SHAREABLE_PERSONAL';
const SET_UNSHAREABLE_PERSONAL = 'SET_UNSHAREABLE_PERSONAL';

module.exports = {
    ADD_DOCUMENT_PERSONAL: ADD_DOCUMENT_PERSONAL,
    REMOVE_DOCUMENT_PERSONAL: REMOVE_DOCUMENT_PERSONAL,
    addDocumentPersonalAction : createAction(ADD_DOCUMENT_PERSONAL),
    removeDocumentPersonalAction : createAction(REMOVE_DOCUMENT_PERSONAL),  
    SET_SHAREABLE_PERSONAL: SET_SHAREABLE_PERSONAL,
    setShareablePersonalAction: createAction(SET_SHAREABLE_PERSONAL),
    SET_UNSHAREABLE_PERSONAL: SET_UNSHAREABLE_PERSONAL,
    setUnshareablePersonalAction: createAction(SET_UNSHAREABLE_PERSONAL),
};