import { createAction } from 'redux-actions';

const ADD_DOCUMENT_PUBLIC = 'ADD_DOCUMENT_PUBLIC';
const REMOVE_DOCUMENT_PUBLIC = 'REMOVE_DOCUMENT_PUBLIC';
const SET_SHAREABLE_PUBLIC = 'SET_SHAREABLE_PUBLIC';
const SET_UNSHAREABLE_PUBLIC = 'SET_UNSHAREABLE_PUBLIC';

module.exports = {
    ADD_DOCUMENT_PUBLIC: ADD_DOCUMENT_PUBLIC,
    REMOVE_DOCUMENT_PUBLIC: REMOVE_DOCUMENT_PUBLIC,
    addDocumentPublicAction : createAction(ADD_DOCUMENT_PUBLIC),
    removeDocumentPublicAction : createAction(REMOVE_DOCUMENT_PUBLIC),
    SET_SHAREABLE_PUBLIC: SET_SHAREABLE_PUBLIC,
    setShareablePublicAction: createAction(SET_SHAREABLE_PUBLIC),
    SET_UNSHAREABLE_PUBLIC: SET_UNSHAREABLE_PUBLIC,
    setUnshareablePublicAction: createAction(SET_UNSHAREABLE_PUBLIC),
};